kind: Deployment
apiVersion: apps/v1
metadata:
  name: uperf-server
  namespace: default
spec:
  template:
    metadata:
      name: uperf-server-1
      labels:
        app: uperf-server-1
        group: kb-mb-wl
    spec:
#      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: benchmark
        image: 'quay.io/cloud-bulldozer/uperf:latest'
        imagePullPolicy: Always
        command: ["/bin/sh","-c"]
        args: ["uperf -s -v -P 30000"]        
  replicas: 1
  selector:
    matchLabels:
      app: uperf-server-1
  triggers:
  - type: ConfigChange
  strategy:
    type: RollingUpdate
 
---
apiVersion: v1
kind: Service
metadata:
  name: uperf-service
  namespace: default
spec:
  ports:
  - name: uperf
    port: 30000
    nodePort: 30000
    protocol: TCP
    targetPort: 30000
  - name: uperf-1
    port: 30001
    nodePort: 30001
    protocol: TCP
    targetPort: 30001
  - name: uperf-2
    port: 30000
    nodePort: 30000
    protocol: UDP
    targetPort: 30000
  - name: uperf-3
    port: 30001
    nodePort: 30001
    protocol: UDP
    targetPort: 30001
  - name: uperf-4
    port: 30002
    nodePort: 30002
    protocol: TCP
    targetPort: 30002
  - name: uperf-5
    port: 30002
    nodePort: 30002
    protocol: UDP
    targetPort: 30002
  - name: uperf-6
    port: 30003
    nodePort: 30003
    protocol: TCP
    targetPort: 30003
  - name: uperf-7
    port: 30004
    nodePort: 30004
    protocol: TCP
    targetPort: 30004
  - name: uperf-8
    port: 30003
    nodePort: 30003
    protocol: UDP
    targetPort: 30003
  - name: uperf-9
    port: 30004
    nodePort: 30004
    protocol: UDP
    targetPort: 30004
  - name: uperf-10
    port: 30005
    nodePort: 30005
    protocol: TCP
    targetPort: 30005
  - name: uperf-11
    port: 30005
    nodePort: 30005
    protocol: UDP
    targetPort: 30005    
  - name: uperf-12
    port: 30006
    nodePort: 30006
    protocol: TCP
    targetPort: 30006
  - name: uperf-13
    port: 30006
    nodePort: 30006
    protocol: UDP
    targetPort: 30006
  - name: uperf-14
    port: 30007
    nodePort: 30007
    protocol: TCP
    targetPort: 30007
  - name: uperf-15
    port: 30008
    nodePort: 30008
    protocol: TCP
    targetPort: 30008
  - name: uperf-16
    port: 30007
    nodePort: 30007
    protocol: UDP
    targetPort: 30007
  - name: uperf-17
    port: 30008
    nodePort: 30008
    protocol: UDP
    targetPort: 30008
  - name: uperf-18
    port: 30009
    nodePort: 30009
    protocol: TCP
    targetPort: 30009
  - name: uperf-19
    port: 30009
    nodePort: 30009
    protocol: UDP
    targetPort: 30009
  - name: uperf-20
    port: 30010
    nodePort: 30010
    protocol: TCP
    targetPort: 30010
  - name: uperf-21
    port: 30010
    nodePort: 30010
    protocol: UDP
    targetPort: 30010
  - name: uperf-22
    port: 30011
    nodePort: 30011
    protocol: TCP
    targetPort: 30011
  - name: uperf-23
    port: 30011
    nodePort: 30011
    protocol: UDP
    targetPort: 30011    
  selector:
    app: uperf-server-1
  type: NodePort
